<?php $this->headTitle()->prepend('Informes del Docente'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/modules/enc/encuesta/get.css')); ?>

<?php if ($this->puedeGenerar): ?>
<div class="links">
    <a href="<?php echo $this->baseUrl('/inf/docente/index'); ?>">&#x21a9; Volver al Listado</a>
</div>

<hr class="separator" />
<?php endif; ?>

<?php if ($this->docente): ?>

    <table class="visualizaciones">
        <tr>
            <th width="10%">CODIGO</th>
            <th width="40%">DOCENTE</th>
            <th width="40%">EMAIL</th>
            <th width="10%">ACTIVO</th>
        </tr>
        <tr>
            <td style="text-align: center;"><?php echo $this->docente["codigo"]; ?></td>
            <td><?php echo $this->docente["docente"]; ?></td>
            <td><?php echo $this->docente["email"]; ?></td>
            <td style="text-align: center;"><?php echo ($this->docente["activo"] == "S") ? ("S&iacute;") : ("No"); ?></td>
        </tr>
    </table>
    
    <dl>
    <?php if (count($this->docente['informes'])): ?>
        <dt>Informes del Docente</dt>
        <?php foreach ($this->docente['informes'] as $informe): ?>
            <dd>
				<li class="report">
					<?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" . $informe['periodo'] . ' - ' .
						$informe["asignatura"] . ' - ' . $informe["departamento"]; ?>
					<br/>
					<a class="get-link" href="ver-informe?id=<?php echo $informe["enc_particular_id"]; ?>">
						Ver Informe
					</a><?php if ($this->puedeGenerar): ?> &nbsp;&nbsp; &nbsp;&nbsp; |
					<a class="get-link" href="gen-informe?id=<?php echo $informe["enc_particular_id"]; ?>">
						Generar Informe
					</a><?php endif; ?>
				</li>
            </dd>
        <?php endforeach; ?>
    <?php else: ?>
        <dt>El docente no tiene informes</dt>
    <?php endif; ?>
    </dl>

<?php endif; ?>

<hr class="separator" />

<?php if ($this->puedeGenerar): ?>
<div class="links">
    <a href="<?php echo $this->baseUrl('/inf/docente/index'); ?>">&#x21a9; Volver al Listado</a>
</div>
<?php endif; ?>