<?php $this->headTitle()->prepend('Docentes'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/modules/enc/plantilla/index.css')); ?>

<div style="margin: 15px auto;">
    <?php if (!count($this->docentes)): ?>
    <div class="warning">
        <img width="50px" alt="Aviso" src="<?php echo $this->baseUrl('images/warning.png'); ?>">
        <br /><h4>Sin docentes.</h4>
    </div>
    <?php else: ?>
    <table>
        <thead>
            <tr>
                <th width="10%">CODIGO</th>
                <th width="40%">DOCENTE</th>
                <th width="40%">EMAIL</th>
                <th width="10%">ACTIVO</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->docentes as $docente): ?>
            <tr>
                <td style="text-align: center;">
                    <a class="get-link" href="get?id=<?php echo $docente["docente_id"]; ?>">
                        <?php echo $docente["codigo"]; ?>
                    </a>
                </td>
                <td>
                    <a class="get-link" href="get?id=<?php echo $docente["docente_id"]; ?>">
                        <?php echo $docente["docente"]; ?>
                    </a>
                </td>
                <td><?php echo $docente["email"]; ?></td>
                <td style="text-align: center;">
                    <?php echo ($docente["activo"] == "S") ? ("S&iacute;") : ("No"); ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</div>