<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Carrera', 'doctrine');

/**
 * Model_Base_Carrera
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $carrera_id
 * @property integer $departamento_id
 * @property string $nombre
 * @property string $codigo
 * @property Model_Departamento $Departamento
 * @property Doctrine_Collection $Asignatura
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Carrera extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('carrera');
        $this->hasColumn('carrera_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'carrera_carrera_id',
             ));
        $this->hasColumn('departamento_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('codigo', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Departamento as Departamento', array(
             'local' => 'departamento_id',
             'foreign' => 'departamento_id'));

        $this->hasMany('Model_Asignatura as Asignatura', array(
             'local' => 'carrera_id',
             'foreign' => 'carrera_id'));
    }
}