<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Categoria', 'doctrine');

/**
 * Model_Base_Categoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $categoria_id
 * @property integer $encuesta_id
 * @property integer $categoria_padre
 * @property string $nombre
 * @property string $descripcion
 * @property integer $orden
 * @property Model_Encuesta $Encuesta
 * @property Model_Categoria $CategoriaPadre
 * @property Doctrine_Collection $Categoria
 * @property Doctrine_Collection $Pregunta
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Categoria extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria');
        $this->hasColumn('categoria_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'categoria_categoria_id',
             ));
        $this->hasColumn('encuesta_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('categoria_padre', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('orden', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Encuesta as Encuesta', array(
             'local' => 'encuesta_id',
             'foreign' => 'encuesta_id'));
        
        $this->hasOne('Model_Categoria as CategoriaPadre', array(
            'local' => 'categoria_padre',
            'foreign' => 'categoria_id'));

        $this->hasMany('Model_Categoria as Categoria', array(
             'local' => 'categoria_id',
             'foreign' => 'categoria_padre'));

        $this->hasMany('Model_Pregunta as Pregunta', array(
             'local' => 'categoria_id',
             'foreign' => 'categoria_id'));
    }
}