<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_DocenteDpto', 'doctrine');

/**
 * Model_Base_DocenteDpto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $docente_dpto_id
 * @property integer $docente_id
 * @property integer $departamento_id
 * @property Model_Departamento $Departamento
 * @property Model_Docente $Docente
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_DocenteDpto extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('docente_dpto');
        $this->hasColumn('docente_dpto_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'docente_dpto_docente_dpto_id',
             ));
        $this->hasColumn('docente_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('departamento_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Departamento as Departamento', array(
             'local' => 'departamento_id',
             'foreign' => 'departamento_id'));

        $this->hasOne('Model_Docente as Docente', array(
             'local' => 'docente_id',
             'foreign' => 'docente_id'));
    }
}