<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Docente', 'doctrine');

/**
 * Model_Base_Docente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $docente_id
 * @property integer $persona_id
 * @property string $codigo
 * @property string $activo
 * @property Model_Persona $Persona
 * @property Doctrine_Collection $EncParticular
 * @property Doctrine_Collection $DocenteDpto
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Docente extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('docente');
        $this->hasColumn('docente_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'docente_docente_id',
             ));
        $this->hasColumn('persona_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('codigo', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('activo', 'string', null, array(
             'type' => 'string',
             'fixed' => true,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Persona as Persona', array(
             'local' => 'persona_id',
             'foreign' => 'persona_id'));

        $this->hasMany('Model_EncParticular as EncParticular', array(
             'local' => 'docente_id',
             'foreign' => 'docente_id'));

        $this->hasMany('Model_DocenteDpto as DocenteDpto', array(
             'local' => 'docente_id',
             'foreign' => 'docente_id'));
    }
}