<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Encuesta', 'doctrine');

/**
 * Model_Base_Encuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $encuesta_id
 * @property integer $escala_id
 * @property string $nombre
 * @property string $descripcion
 * @property date $fecha
 * @property string $activo
 * @property Model_Escala $Escala
 * @property Doctrine_Collection $Pregunta
 * @property Doctrine_Collection $EncParticular
 * @property Doctrine_Collection $Categoria
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Encuesta extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('encuesta');
        $this->hasColumn('encuesta_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'encuesta_encuesta_id',
             ));
        $this->hasColumn('escala_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('activo', 'string', null, array(
             'type' => 'string',
             'fixed' => true,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Escala as Escala', array(
             'local' => 'escala_id',
             'foreign' => 'escala_id'));

        $this->hasMany('Model_Pregunta as Pregunta', array(
             'local' => 'encuesta_id',
             'foreign' => 'encuesta_id'));

        $this->hasMany('Model_EncParticular as EncParticular', array(
             'local' => 'encuesta_id',
             'foreign' => 'encuesta_id'));

        $this->hasMany('Model_Categoria as Categoria', array(
             'local' => 'encuesta_id',
             'foreign' => 'encuesta_id'));
    }
}