<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_EscalaValor', 'doctrine');

/**
 * Model_Base_EscalaValor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $escala_valor_id
 * @property integer $escala_id
 * @property integer $valor
 * @property string $descripcion
 * @property Model_Escala $Escala
 * @property Doctrine_Collection $RespDetalle
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_EscalaValor extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('escala_valor');
        $this->hasColumn('escala_valor_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'escala_valor_escala_valor_id',
             ));
        $this->hasColumn('escala_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('valor', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Escala as Escala', array(
             'local' => 'escala_id',
             'foreign' => 'escala_id'));

        $this->hasMany('Model_RespDetalle as RespDetalle', array(
             'local' => 'escala_valor_id',
             'foreign' => 'escala_valor_id'));
    }
}