<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Escala', 'doctrine');

/**
 * Model_Base_Escala
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $escala_id
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $EscalaValor
 * @property Doctrine_Collection $Encuesta
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Escala extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('escala');
        $this->hasColumn('escala_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'escala_escala_id',
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_EscalaValor as EscalaValor', array(
             'local' => 'escala_id',
             'foreign' => 'escala_id'));

        $this->hasMany('Model_Encuesta as Encuesta', array(
             'local' => 'escala_id',
             'foreign' => 'escala_id'));
    }
}