<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Facultad', 'doctrine');

/**
 * Model_Base_Facultad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $facultad_id
 * @property string $nombre
 * @property string $codigo
 * @property Doctrine_Collection $Departamento
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Facultad extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('facultad');
        $this->hasColumn('facultad_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'facultad_facultad_id',
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('codigo', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_Departamento as Departamento', array(
             'local' => 'facultad_id',
             'foreign' => 'facultad_id'));
    }
}