<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Periodo', 'doctrine');

/**
 * Model_Base_Periodo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $periodo_id
 * @property string $periodo
 * @property Doctrine_Collection $PeriodoLectivo
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Periodo extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('periodo');
        $this->hasColumn('periodo_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'periodo_periodo_id',
             ));
        $this->hasColumn('periodo', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_PeriodoLectivo as PeriodoLectivo', array(
             'local' => 'periodo_id',
             'foreign' => 'periodo_id'));
    }
}