<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Persona', 'doctrine');

/**
 * Model_Base_Persona
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $persona_id
 * @property string $nombre
 * @property string $apellido
 * @property string $email
 * @property string $es_docente
 * @property Doctrine_Collection $Usuario
 * @property Doctrine_Collection $Docente
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Persona extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('persona');
        $this->hasColumn('persona_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'persona_persona_id',
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('apellido', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('email', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('es_docente', 'string', null, array(
             'type' => 'string',
             'fixed' => true,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_Usuario as Usuario', array(
             'local' => 'persona_id',
             'foreign' => 'persona_id'));

        $this->hasMany('Model_Docente as Docente', array(
             'local' => 'persona_id',
             'foreign' => 'persona_id'));
    }
}