<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Pregunta', 'doctrine');

/**
 * Model_Base_Pregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pregunta_id
 * @property integer $encuesta_id
 * @property integer $categoria_id
 * @property string $pregunta
 * @property string $descripcion
 * @property string $tipo
 * @property string $es_obligatoria
 * @property string $opcion_multiple
 * @property integer $orden
 * @property Model_Encuesta $Encuesta
 * @property Model_Categoria $Categoria
 * @property Doctrine_Collection $PreguntaSm
 * @property Doctrine_Collection $RespDetalle
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Pregunta extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('pregunta');
        $this->hasColumn('pregunta_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'pregunta_pregunta_id',
             ));
        $this->hasColumn('encuesta_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('categoria_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('pregunta', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('tipo', 'string', null, array(
             'type' => 'string',
             'fixed' => true,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('es_obligatoria', 'string', null, array(
             'type' => 'string',
             'fixed' => true,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('opcion_multiple', 'string', null, array(
             'type' => 'string',
             'fixed' => true,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('orden', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Encuesta as Encuesta', array(
             'local' => 'encuesta_id',
             'foreign' => 'encuesta_id'));

        $this->hasOne('Model_Categoria as Categoria', array(
             'local' => 'categoria_id',
             'foreign' => 'categoria_id'));

        $this->hasMany('Model_PreguntaSm as PreguntaSm', array(
             'local' => 'pregunta_id',
             'foreign' => 'pregunta_id'));

        $this->hasMany('Model_RespDetalle as RespDetalle', array(
             'local' => 'pregunta_id',
             'foreign' => 'pregunta_id'));
    }
}