<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_RespDetalle', 'doctrine');

/**
 * Model_Base_RespDetalle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $resp_detalle_id
 * @property integer $respuesta_id
 * @property integer $pregunta_id
 * @property integer $escala_valor_id
 * @property string $respuesta
 * @property Model_Respuesta $Respuesta
 * @property Model_Pregunta $Pregunta
 * @property Model_EscalaValor $EscalaValor
 * @property Doctrine_Collection $OpcionElegida
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_RespDetalle extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('resp_detalle');
        $this->hasColumn('resp_detalle_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'resp_detalle_resp_detalle_id',
             ));
        $this->hasColumn('respuesta_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('pregunta_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             ));
        $this->hasColumn('escala_valor_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('respuesta', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Respuesta as Respuesta', array(
             'local' => 'respuesta_id',
             'foreign' => 'respuesta_id'));

        $this->hasOne('Model_Pregunta as Pregunta', array(
             'local' => 'pregunta_id',
             'foreign' => 'pregunta_id'));

        $this->hasOne('Model_EscalaValor as EscalaValor', array(
             'local' => 'escala_valor_id',
             'foreign' => 'escala_valor_id'));

        $this->hasMany('Model_OpcionElegida as OpcionElegida', array(
             'local' => 'resp_detalle_id',
             'foreign' => 'resp_detalle_id'));
    }
}