<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_ResultadoDepartamento', 'doctrine');

/**
 * Model_Base_EncParticular
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $resultado
 * @property integer $enc_particular_id
 * @property date $fecha
 * @property string $texto
 * @property float $promedio
 * @property string $nota
 * @property boolean $bold
 * @property integer $part
 * @property Model_EncParticular $EncParticular
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_ResultadoDepartamento extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('resultados_departamento');
        $this->hasColumn('resultado', 'integer', 4, array(
            'type' => 'integer',
            'length' => 4,
            'fixed' => false,
            'unsigned' => false,
            'primary' => true
            //'sequence' => 'resultados_departamento_seq',
        ));
        $this->hasColumn('enc_particular_id', 'integer', 4, array(
            'type' => 'integer',
            'length' => 4,
            'fixed' => false,
            'unsigned' => false,
            'notnull' => true,
            'primary' => false,
        ));
        $this->hasColumn('fecha', 'date', 4, array(
            'type' => 'date',
            'fixed' => false,
            'unsigned' => false,
            'notnull' => false,
            'primary' => false,
        ));
        $this->hasColumn('texto', 'text', null, array(
            'type' => 'text',
            'fixed' => false,
            'unsigned' => false,
            'notnull' => false,
            'primary' => false,
        ));
        $this->hasColumn('promedio', 'float', 4, array(
            'type' => 'float',
            'fixed' => false,
            'unsigned' => false,
            'notnull' => false,
            'primary' => false,
        ));
        $this->hasColumn('nota', 'string', null, array(
            'type' => 'string',
            'fixed' => true,
            'unsigned' => false,
            'notnull' => false,
            'primary' => false,
        ));
        $this->hasColumn('bold', 'boolean', 1, array(
            'type' => 'boolean',
            'fixed' => true,
            'unsigned' => false,
            'notnull' => true,
            'primary' => false,
        ));
        $this->hasColumn('part', 'integer', 2, array(
            'type' => 'integer',
            'length' => 4,
            'fixed' => true,
            'unsigned' => false,
            'notnull' => true,
            'primary' => false,
        ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_EncParticular as EncParticular', array(
            'local' => 'enc_particular_id',
            'foreign' => 'enc_particular_id'));
    }
}