<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_ResultadoMateria', 'doctrine');

/**
 * Model_Base_EncParticular
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $resultado
 * @property integer $asignatura_id
 * @property integer $periodo_lectivo_id
 * @property date $fecha
 * @property string $texto
 * @property float $promedio
 * @property string $nota
 * @property boolean $bold
 * @property integer $part
 * @property Model_Asignatura $Asignatura
 * @property Model_PeriodoLectivo $PeriodoLectivo
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_ResultadoMateria extends Doctrine_Record
{
	public function setTableDefinition()
	{
		$this->setTableName('resultados_materia');
		$this->hasColumn('resultado', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'fixed' => false,
			'unsigned' => false,
			'primary' => true
			//'sequence' => 'resultados_departamento_seq',
		));
		$this->hasColumn('asignatura_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'fixed' => false,
			'unsigned' => false,
			'notnull' => true,
			'primary' => false,
		));
		$this->hasColumn('periodo_lectivo_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'fixed' => false,
			'unsigned' => false,
			'notnull' => true,
			'primary' => false,
		));
		$this->hasColumn('fecha', 'date', 4, array(
			'type' => 'date',
			'fixed' => false,
			'unsigned' => false,
			'notnull' => false,
			'primary' => false,
		));
		$this->hasColumn('texto', 'text', null, array(
			'type' => 'text',
			'fixed' => false,
			'unsigned' => false,
			'notnull' => false,
			'primary' => false,
		));
		$this->hasColumn('promedio', 'float', 4, array(
			'type' => 'float',
			'fixed' => false,
			'unsigned' => false,
			'notnull' => false,
			'primary' => false,
		));
		$this->hasColumn('nota', 'string', null, array(
			'type' => 'string',
			'fixed' => true,
			'unsigned' => false,
			'notnull' => false,
			'primary' => false,
		));
		$this->hasColumn('bold', 'boolean', 1, array(
			'type' => 'boolean',
			'fixed' => true,
			'unsigned' => false,
			'notnull' => true,
			'primary' => false,
		));
		$this->hasColumn('part', 'integer', 2, array(
			'type' => 'integer',
			'length' => 4,
			'fixed' => true,
			'unsigned' => false,
			'notnull' => true,
			'primary' => false,
		));
	}

	public function setUp()
	{
		parent::setUp();
		$this->hasOne('Model_Asignatura as Asignatura', array(
			'local' => 'asignatura_id',
			'foreign' => 'asignatura_id'));

		$this->hasOne('Model_PeriodoLectivo as PeriodoLectivo', array(
			'local' => 'periodo_lectivo_id',
			'foreign' => 'periodo_lectivo_id'));
	}
}