<?php $this->headTitle()->prepend('Completar Encuesta'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/modules/resp/encuesta/get.css')); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/modules/resp/encuesta/complete.css')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('js/modules/resp/encuesta/complete.js')); ?>

<div id="cabecera">

<div class="detalle">
    <label>Docente: </label><?php echo $this->encuesta["docente"]; ?>
    <span class="separator"></span>
    |
    <span class="separator"></span>
    <label>Asignatura: </label><?php echo $this->encuesta["asignatura"]; ?>
    <span class="separator"></span>
    |
    <span class="separator"></span>
    <label>Periodo Lectivo: </label><?php echo $this->encuesta["periodo"]; ?>
</div>

<hr class="separator" />

<div><h3 class="encuesta-title"><?php echo $this->plantilla["encuesta"]; ?></h3></div>

<div class="escala-utilizada">
	<h5>Escala:<span class="separator"></span></h5>
	<ul class="escala">
	<?php foreach ($this->plantilla["valores"] as $valor): ?>
		<li><span class="separator"></span><b><?php echo '(' . $valor["valor"] . ') '; ?></b><?php echo $valor["descrip"]; ?></li>
	<?php endforeach; ?>
	</ul>
</div>

<hr class="separator" />

</div>


<form id="completar-encuesta" action="complete?id=<?php echo $this->encuesta["identificador"]; ?>" method="post">
    <input type="hidden" name="enc_particular_id" id="enc_particular_id" value="<?php echo $this->encuesta["enc_particular_id"]; ?>" />
    <input type="hidden" name="identificador" id="identificador" value="<?php echo $this->encuesta["identificador"]; ?>" />

	<?php if ($this->encuesta["password"] != ""): ?>
		<label for="password">Contraseña de la encuesta:</label>
		<input type="text" name="password" id="password" value="" /><br />
	<?php endif; ?>

    <table class="encuesta">
        <thead>
            <tr><th colspan="2"></th><th class="answer-field">CALIFICACION</th></tr>
        </thead>
        
        <tbody>
        <?php $catEnum = 65; $pregEnum = 1; $inputEnum = 1; ?>
        <?php foreach ($this->plantilla["Categorias"] as $categoria): ?>
            <tr class="categoria">
                <td colspan="3"><?php echo chr($catEnum) . '. ' . $categoria["categoria"]; ?></td>
            </tr>
            
            <tbody>
            <?php foreach ($categoria["Preguntas"] as $catPregunta): ?>
            
            <?php if ($catPregunta["tipo"] == 'A'): ?>
            <tr class="pregunta-abierta">
                <td class="enum">
				    <?php if ($catPregunta["es_obligatoria"] == "S"): ?>
				        <span class="required-field"> * </span>
				    <?php endif; ?>
				    <?php echo $pregEnum++ ?>
				</td>
				
    			<td colspan="2">
    			    <?php echo $catPregunta["pregunta"]; ?><br>
    			    <textarea obligatoria="<?php echo $catPregunta["es_obligatoria"];?>" class="answer-pregunta-abierta" placeholder="Escriba su respuesta aqui" cols="105" name="respuestas[A][<?php echo $catPregunta["pregunta_id"]; ?>]" tabindex="<?php echo $inputEnum++; ?>"></textarea>
			    </td>
		    </tr>
		    
			<?php elseif ($catPregunta["tipo"] == 'E'): ?>
			<tr class="pregunta-escala">
			    <td class="enum">
				    <?php if ($catPregunta["es_obligatoria"] == "S"): ?>
				        <span class="required-field"> * </span>
				    <?php endif; ?>
				    <?php echo $pregEnum++; ?>
			    </td>
			    
			    <td><?php echo $catPregunta["pregunta"]; ?></td>
			    
			    <td class="answer-field">
			        <select obligatoria="<?php echo $catPregunta["es_obligatoria"]; ?>" class="answer-pregunta-escalada" name="respuestas[E][<?php echo $catPregunta["pregunta_id"]; ?>]" tabindex="<?php echo $inputEnum++; ?>">
    				    <option 'selected="selected" value="none"> ----- </option>
				<?php $escalaDesc = array( 4 => "Siempre", 3 => "La mayor parte de las veces", 2 => "La menor parte de las veces", 1 => "Nunca", 9 => "No aplica"); ?>
            			<?php foreach ($this->escala as $valor): ?>
            				<option value="<?php echo $valor["valor_id"]; ?>"><?php echo $escalaDesc[$valor["valor"]]; ?></option>
            			<?php endforeach; ?>
				    </select>
				</td>
			</tr>
			
			<?php elseif ($catPregunta["tipo"] == 'S'): ?>
			<tr class="pregunta-seleccion">
				<td class="enum" rowspan="2">
				    <?php if ($catPregunta["es_obligatoria"] == "S"): ?>
    			        <span class="required-field"> * </span>
    			    <?php endif; ?>
    			    <?php echo $pregEnum++; ?>
			    </td>
				<td colspan="2"><?php echo $catPregunta["pregunta"]; ?></td>
			</tr>
			<tr class="pregunta-seleccion">
			    <td colspan="2" class="opciones" obligatoria="<?php echo $catPregunta["es_obligatoria"]; ?>">
    		        <?php $typeSm = ($catPregunta["opcion_multiple"] == "S") ? ('checkbox') : ('radio'); ?>
    				<?php foreach ($catPregunta["Opciones"] as $opcion): ?>
    				    <span class="separator"></span>
    				    <input type="<?php echo $typeSm; ?>" name="respuestas[S][<?php echo $catPregunta["pregunta_id"]; ?>][]" value="<?php echo $opcion["pregunta_sm_id"]; ?>" tabindex="<?php echo $inputEnum; ?>">
    				    <?php echo $opcion["nombre"]; ?><br />
    				<?php endforeach; ?>
    				<?php $inputEnum++; ?>
    			</td>
			</tr>
			<?php endif; ?>
			<?php endforeach; ?>
			
		</tbody>
		
		<tbody>
		<?php $subCatEnum = 1; ?>
		<?php foreach ($categoria["Categorias"] as $subCategoria): ?>
			<tr class="subcategoria">
				<td colspan="3"><?php echo chr($catEnum) . '.' . $subCatEnum . '. ' . $subCategoria["categoria"]; ?></td>
			</tr>
			<tbody>
				<?php foreach ($subCategoria["Preguntas"] as $subPregunta): ?>
				<?php if ($subPregunta["tipo"] == 'A'): ?>
				<tr class="pregunta-abierta">
				    <td class="enum">
					    <?php if ($subPregunta["es_obligatoria"] == "S"): ?>
    				        <span class="required-field"> * </span>
    				    <?php endif; ?>
    				    <?php echo $pregEnum++; ?>
				    </td>
				    
        		    <td colspan="2">
        			    <?php echo $subPregunta["pregunta"]; ?><br>
        			    <textarea obligatoria="<?php echo $subPregunta["es_obligatoria"];?>" class="answer-pregunta-abierta" placeholder="Escriba su respuesta aqui" cols="105" name="respuestas[A][<?php echo $subPregunta["pregunta_id"]; ?>]" tabindex="<?php echo $inputEnum++; ?>"></textarea>
    			    </td>
        		</tr>
        		
				<?php elseif ($subPregunta["tipo"] == 'E'): ?>
				<tr class="pregunta-escala">
				    <td class="enum">
					    <?php if ($subPregunta["es_obligatoria"] == "S"): ?>
    				        <span class="required-field"> * </span>
    				    <?php endif; ?>
					    <?php echo $pregEnum++; ?>
					</td>
					
					<td><?php echo $subPregunta["pregunta"]; ?></td>
					
					<td class="answer-field">
					    <select obligatoria="<?php echo $subPregunta["es_obligatoria"]; ?>" class="answer-pregunta-escalada" name="respuestas[E][<?php echo $subPregunta["pregunta_id"]; ?>]" tabindex="<?php echo $inputEnum++; ?>">
        				    <option 'selected="selected" value="none"> ----- </option>
					<?php $escalaDesc = array( 4 => "Siempre", 3 => "La mayor parte de las veces", 2 => "La menor parte de las veces", 1 => "Nunca", 9 => "No aplica"); ?>
                			<?php foreach ($this->escala as $valor): ?>
                			    <option value="<?php echo $valor["valor_id"]; ?>"><?php echo $escalaDesc[$valor["valor"]]; ?></option>
                			<?php endforeach; ?>
    				    </select>
					</td>
				</tr>
				
				<?php elseif ($subPregunta["tipo"] == 'S'): ?>
				<tr class="pregunta-seleccion">
					<td class="enum" rowspan="2">
					    <?php if ($subPregunta["es_obligatoria"] == "S"): ?>
        			        <span class="required-field"> * </span>
        			    <?php endif; ?>
        			    <?php echo $pregEnum++; ?>
    			    </td>
					<td colspan="2"><?php echo $subPregunta["pregunta"]; ?></td>
				</tr>
				<tr class="pregunta-seleccion">
				    <td colspan="2" class="opciones" obligatoria="<?php echo $subPregunta["es_obligatoria"]; ?>">
        		        <?php $typeSm = ($subPregunta["opcion_multiple"] == "S") ? ('checkbox') : ('radio'); ?>
        				<?php foreach ($subPregunta["Opciones"] as $opcion): ?>
        				    <span class="separator"></span>
        				    <input type="<?php echo $typeSm; ?>" name="respuestas[S][<?php echo $subPregunta["pregunta_id"]; ?>][]" value="<?php echo $opcion["pregunta_sm_id"]; ?>" tabindex="<?php echo $inputEnum; ?>">
    				        <?php echo $opcion["nombre"]; ?><br />
        				<?php endforeach; ?>
        				<?php $inputEnum++; ?>
        			</td>
				</tr>
				<?php endif; ?>
				<?php endforeach; ?>
			</tbody>
		<?php $subCatEnum++; ?>
		<?php endforeach; ?>
		</tbody>
		<?php $catEnum++; ?>
	<?php endforeach; ?>
	<?php foreach ($this->plantilla["Preguntas"] as $pregunta): ?>
	
		<?php if ($pregunta["tipo"] == 'A'): ?>
		<tr class="pregunta-abierta">
		    <td class="enum">
			    <?php if ($pregunta["es_obligatoria"] == "S"): ?>
			        <span class="required-field"> * </span>
			    <?php endif; ?>
			    <?php echo $pregEnum++; ?>
		    </td>
		    
		    <td colspan="2">
			    <?php echo $pregunta["pregunta"]; ?><br>
			    <textarea obligatoria="<?php echo $pregunta["es_obligatoria"];?>" class="answer-pregunta-abierta" placeholder="Escriba su respuesta aqui" cols="105" name="respuestas[A][<?php echo $pregunta["pregunta_id"]; ?>]" tabindex="<?php echo $inputEnum++; ?>"></textarea>
		    </td>
		</tr>
		
		<?php elseif ($pregunta["tipo"] == 'E'): ?>
		<tr class="pregunta-escala">
			<td class="enum">
			    <?php if ($pregunta["es_obligatoria"] == "S"): ?>
			        <span class="required-field"> * </span>
			    <?php endif; ?>
			    <?php echo $pregEnum++; ?>
		    </td>
		    
			<td><?php echo $pregunta["pregunta"]; ?></td>
			
			<td class="answer-field">
			    <select obligatoria="<?php echo $pregunta["es_obligatoria"]; ?>" class="answer-pregunta-escalada" name="respuestas[E][<?php echo $pregunta["pregunta_id"]; ?>]" tabindex="<?php echo $inputEnum++; ?>">
				    <option 'selected="selected" value="none"> ----- </option>
        			<?php $escalaDesc = array( 4 => "Siempre", 3 => "La mayor parte de las veces", 2 => "La menor parte de las veces", 1 => "Nunca", 9 => "No aplica"); ?>
				<?php foreach ($this->escala as $valor): ?>
        			    <option value="<?php echo $valor["valor_id"]; ?>"><?php echo $escalaDesc[$valor["valor"]]; ?></option>
        			<?php endforeach; ?>
			    </select>
			</td>
		</tr>
		<?php elseif ($pregunta["tipo"] == 'S'): ?>
		<tr class="pregunta-seleccion">
		    <td class="enum" rowspan="2">
			    <?php if ($pregunta["es_obligatoria"] == "S"): ?>
			        <span class="required-field"> * </span>
			    <?php endif; ?>
			    <?php echo $pregEnum++; ?>
		    </td>
			<td colspan="2"><?php echo $pregunta["pregunta"]; ?></td>
		</tr>
		<tr class="pregunta-seleccion">
		    <td colspan="2" class="opciones" obligatoria="<?php echo $pregunta["es_obligatoria"]; ?>">
		        <?php $typeSm = ($pregunta["opcion_multiple"] == "S") ? ('checkbox') : ('radio'); ?>
				<?php foreach ($pregunta["Opciones"] as $opcion): ?>
				    <span class="separator"></span>
				    <input type="<?php echo $typeSm; ?>" name="respuestas[S][<?php echo $pregunta["pregunta_id"]; ?>][]" value="<?php echo $opcion["pregunta_sm_id"]; ?>" tabindex="<?php echo $inputEnum; ?>">
				    <?php echo $opcion["nombre"]; ?><br />
				<?php endforeach; ?>
				<?php $inputEnum++; ?>
			</td>
		</tr>
		<?php endif; ?>
	<?php endforeach; ?>
	</tbody>
</table>

<input id="send-form" type="submit" value="Enviar Respuesta" title="Debe responder todas las preguntas obligatorias" tabindex="<?php echo $inputEnum; ?>" />

</form>
