<?php $this->headLink()->appendStylesheet($this->baseUrl('css/modules/resp/encuesta/no-activo.css')); ?>

<div class="center">
	<img width="50px" alt="Aviso" src="<?php echo $this->baseUrl('images/warning.png'); ?>">
	<br /><br />

	<p>
		Lo sentimos.<br />
		El password ingresado es incorrecto.<br />
		Contacte con el encargado de la encuesta.
	</p>

	<script>
		document.write('<a href="' + document.referrer + '">Volver</a>');
	</script>
</div>