<?php $this->headLink()->appendStylesheet($this->baseUrl('css/modules/resp/encuesta/no-activo.css')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('js/modules/resp/encuesta/success.js')); ?>

<div class="center">
    <img width="50px" alt="Aviso" src="<?php echo $this->baseUrl('images/ok.png'); ?>">
    <br /><br />
    
    <p>
        Agradecemos sus respuestas.
    </p>
    
    <a id="close">CERRAR VENTANA</a>
</div>