<h2>
	III. <?php echo $this->data["asignatura"]." - ".$this->data["periodo"]; ?>
</h2>

<h3>
	Cantidad de Cursos Promediados: <?php echo $this->cant_mat; ?>
</h3>
<br>


<p style="margin-top: -20px; font-style: italic; color: #223359;">
    <span class="resaltado">N&uacute;mero de respuestas recibidas:
		<?php echo $this->cant_resp; ?> (Equivale al
		<?php echo $this->porcentaje; ?>% del Universo)</span>
</p>

<br>
<h5>Puntajes obtenidos por categorias</h5>
<table>
	<tr>
		<th style="text-align: center; width: 70%;">GRANDES CATEGORIAS (puntuaci&oacute;n del 1 al 4)</th>
		<th style="text-align: center;">PROMEDIO</th>
		<th style="text-align: center;">NOTA</th>
	</tr>
	<?php foreach ($this->encuesta['Categorias'] as $categoria): ?>
		<tr>
			<td><?php echo $categoria['categoria']; ?></td>
			<td style="text-align: center;"><?php echo $categoria['promedio']; ?></td>
			<td style="text-align: center;"><?php echo $categoria['nota']; ?></td>
		</tr>

		<?php foreach ($categoria['Categorias'] as $subCategoria): ?>
			<tr>
				<td><?php echo $subCategoria['categoria']; ?></td>
				<td style="text-align: center;"><?php echo $subCategoria['promedio']; ?></td>
				<td style="text-align: center;"><?php echo $subCategoria['nota']; ?></td>
			</tr>
		<?php endforeach; ?>

	<?php endforeach; ?>
</table>

<h5>Promedios de la asignatura</h5>

<table>
	<tr>
		<th style="text-align: center; width: 70%;">GRANDES CATEGORIAS (puntuaci&oacute;n del 1 al 4)</th>
		<th style="text-align: center;">PROMEDIO</th>
		<th style="text-align: center;">NOTA</th>
	</tr>
	<?php foreach ($this->encuesta['Categorias'] as $categoria): ?>
		<tr>
			<td style="font-weight: bold;"><?php echo $categoria['categoria']; ?></td>
			<td></td>
			<td></td>
		</tr>
		<?php foreach ($categoria['Preguntas'] as $pregunta): ?>
			<tr>
				<td><?php echo $pregunta['pregunta']; ?></td>
				<td style="text-align: center;"><?php echo $pregunta['promedio']; ?></td>
				<td style="text-align: center;"><?php echo $pregunta['nota']; ?></td>
			</tr>
		<?php endforeach; ?>

		<?php foreach ($categoria['Categorias'] as $subCategoria): ?>
			<tr>
				<td style="font-style: italic; font-weight: bold;"><?php echo $subCategoria['categoria']; ?></td>
				<td></td>
				<td></td>
			</tr>
			<?php foreach ($subCategoria['Preguntas'] as $pregunta): ?>
				<tr>
					<td><?php echo $pregunta['pregunta']; ?></td>
					<td style="text-align: center;"><?php echo $pregunta['promedio']; ?></td>
					<td style="text-align: center;"><?php echo $pregunta['nota']; ?></td>
				</tr>
			<?php endforeach; ?>
		<?php endforeach; ?>
	<?php endforeach; ?>
</table>