<h2>
    III. Perfil de docentes y materias
</h2>

<p>
    Para describir el perfil de los docentes y sus materias se expondr&aacute; en primer lugar 
    el resultado de las grandes dimensiones. Luego de ello se presentan los &iacute;tems (el 
    desagregado de las dimensiones y subdimensiones) en los que el docente sobresale y aquellos 
    en los que tuvo puntuaciones m&aacute;s bajas. Sobre los puntajes.
</p>

<ol>
    <li>
        Para la evaluaci&oacute;n del desempe&ntilde;o docente hay notas de 1 al 5, donde:
        
        <ul>
            <li>1 es Insuficiente</li>
            <li>2 es Aceptable</li>
            <li>3 es Bueno</li>
            <li>4 es Muy Bueno</li>
            <li>5 es Excelente</li>
        </ul>
        
    </li>
    
    <li>
        Para las dimensiones y los &iacute;tems agrupados en las grandes dimensiones las notas 
        son de 1 a 4, donde:
        
        <ul>
            <li>4 es (cumple) siempre</li>
            <li>3 es (cumple) la mayor parte de las veces</li>
            <li>2 es (cumple) la menor parte de las veces</li>
            <li>1 es (cumple) nunca</li>
        </ul>
        
    </li>
</ol>

<p>
    La escala elaborada para las dimensiones y los &iacute;tems agrupados en ellas ha sido:
</p>

<ol>
    <ul>
        <li>1,0 - 2,0 (Deficitario)</li>
        <li>2,1 - 2,6 (Insuficiente)</li>
        <li>2,7 - 3,2 (Aceptable)</li>
        <li>3,3 - 3,7 (Bueno)</li>
        <li>3,8 - 4,0 (Excelente)</li>
    </ul>
</ol>

<p>
    Las puntuaciones altas que ser&aacute;n expuestas primeramente en el perfil de cada 
    docente ser&aacute;n las correspondientes a los tres primeros &iacute;tems más elevados 
    en el caso que &eacute;stos tengan una nota inferior a 3,8. Si el docente recogi&oacute; 
    m&aacute;s de tres &iacute;tems con 4,0, 3,9 o 3,8 se incluir&aacute;n todos. 
    Ser&aacute;n consideradas puntuaciones bajas las que se sit&uacute;an por debajo de 
    3,3 (aceptable).
</p>

<p>
    Se anotar&aacute; igualmente aquello por lo cual el profesor se ve limitado. Cabe 
    destacar en este punto, que la nota m&aacute;xima de la &quot;limitación&quot; es 
    uno y la m&iacute;nima cero. Por tanto, lo positivo en cuanto a las limitaciones es 
    tener como nota cero.
</p>

<p>
    Al final del an&aacute;lisis de los mayores y menores puntajes se incluyen todos los 
    &iacute;tems y categor&iacute;as con sus respectivos puntajes.
</p>