<?php $this->headLink()->appendStylesheet($this->baseUrl('css/modules/inf/informe.css')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('js/modules/inf/informe.js')); ?>

<div id="indice" class="fixed">
	<div class="links">
		<a href="<?php echo $this->baseUrl('/inf/materia/set-periodo?materia=' . $this->asignatura_id); ?>">&#x21a9; VOLVER</a>
		<br/>
		<a href="<?php echo $this->baseUrl('/inf/materia/inf-pdf?materia_id=' . $this->asignatura_id .
		'&periodo_lectivo_id=' . $this->periodo_id); ?>">VERSION PDF</a>
		<br/>
		<a href="<?php echo $this->baseUrl('/inf/materia/inf-xls?materia_id=' . $this->asignatura_id .
		'&periodo_lectivo_id=' . $this->periodo_id); ?>">VERSION EXCEL</a>
	</div>

	<div class="propietario">
		<?php echo $this->data['asignatura'] . '<br>' . $this->data['periodo']; ?>
	</div>

	<h5>INDICE</h5>
	<ol class="indice">
		<li class="indice"><a id="indice-introduccion">Introducci&oacute;n</a></li>
		<li class="indice"><a id="indice-glosario">Glosario de Conceptos</a></li>
		<li class="indice">
			<a id="indice-perfil">Perfil de los docentes y materias</a>
			<ul>
				<li class="indice"><a id="indice-nota-materia">Nota media de la Asignatura</a></li>
			</ul>
		</li>
	</ol>
</div>

<div id="informe">
	<div class="oculto" id="introduccion">
		<?php echo $this->introduccion; ?>
		<br />
		<a class="up">Subir &uarr;</a>
	</div>

	<div class="oculto" style="display: none;" id="glosario">
		<?php echo $this->glosario; ?>
		<hr />
		<a class="up">Subir &uarr;</a>
	</div>

	<div class="oculto" style="display: none;" id="perfil">
		<?php echo $this->perfil; ?>
		<hr />
		<a class="up">Subir &uarr;</a>
	</div>

	<div class="oculto" style="display: none;" id="media-dpto">
		<?php echo $this->mediaDpto; ?>
		<hr />
		<a class="up">Subir &uarr;</a>
	</div>

	<div class="oculto" style="display: none;" id="nota-docente">
		<?php echo $this->notaDocente; ?>
		<hr />
		<a class="up">Subir &uarr;</a>
	</div>

	<div class="oculto" style="display: none;" id="nota-materia">
		<?php echo $this->notaMateria; ?>
		<hr />
		<a class="up">Subir &uarr;</a>
	</div>
</div>