<?php echo $this->doctype(); ?>
<html>

<head>
    <?php echo $this->headTitle(); ?>
    
    <!-- CSS -->
    <?php echo $this->headLink(); ?>
    <!-- End CSS -->
    
    <!-- JS -->
    <?php echo $this->headScript(); ?>
    <!-- End JS -->
</head>

<body>
    
    <div id="main-container">
    
        <!-- HEADER -->
        <div id="header">
            <div id="header-container" class="container">
                <div id="main-logo">
                    <a href="<?php echo $this->baseUrl(); ?>/index/index">
                        <img alt="UC" width="120px" height="120px" src="<?php echo $this->baseUrl('images/logo-uca.png'); ?>" />
                    </a>
                </div>
                
                <div id="main-banner">
                    <a href="<?php echo $this->baseUrl(); ?>/index/index">
                        <img alt="Encuestas Web" src="<?php echo $this->baseUrl('images/main-banner.jpg'); ?>" />
                    </a>
                </div>
            </div>
        </div>
        
        <div id="menu">
            <div id="menu-container" class="container">
                <ul class="menu-bar">
                    <li>
                        <a>INICIAR SESION</a>
                    </li>
                </ul>
            </div>
        </div>
        
        <!-- CONTENT -->
        <div id="content">
            <div id="content-container" class="container">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
        
        <!-- FOOTER -->
        <div id="footer">
            <div id="footer-container" class="container">
                Universidad Cat&oacute;lica &quot;Nuestra Se&ntilde;ora de la Asunci&oacute;n&quot;
                <br />
                Facultad de Ciencias y Tecnolog&iacute;a - DEI
                <br />
                Desarrollado por Guido Arce &amp; Diosnel Vel&aacute;zquez
                <br />
                &copy; 2013
            </div>
        </div>
    
    </div>
    
</body>

</html>