<?php

/**
 * Model_Docente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Docente extends Model_Base_Docente
{
    public function getNombre()
    {
        $apellido = $this->Persona->apellido;
        $nombre   = $this->Persona->nombre;
        
        return $apellido . ', ' . $nombre;
    }
    
    public function addCodigo()
    {
        $query = Doctrine_Query::create()
            ->addSelect('max(d.codigo) as codigo')
            ->from('Model_Docente d');
        $codigo = $query->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
        return intval($codigo['codigo']) + 1;
    }
}