<?php

/**
 * Model_Escala
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Escala extends Model_Base_Escala
{
	public function getValores()
	{
		$valores = array();
		
		foreach ($this->EscalaValor as $valor) {
			$valores[] = array(
			    "valor_id" => $valor->escala_valor_id,
				"valor"    => $valor->valor,
				"descrip"  => $valor->descripcion,
			);
		}
		
		return $valores;
	}
	
	public function borrar()
	{
		foreach ($this->EscalaValor as $valor) {
			$valor->borrar();
		}
		
		$this->delete();
	}
}