<?php

/**
 * Model_EscalaValor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_EscalaValor extends Model_Base_EscalaValor
{
	public function borrar()
	{
		$this->delete();
	}
}