<?php

/**
 * Model_PeriodoLectivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_PeriodoLectivo extends Model_Base_PeriodoLectivo
{
    public function getPeriodoLectivo()
    {
        $periodo = $this->Periodo->periodo;
        $anho    = $this->anho_lectivo;
        
        return $periodo . ' ' . $anho;
    }
}