<?php

/**
 * Model_PreguntaSm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_PreguntaSm extends Model_Base_PreguntaSm
{
    public function getOpciones()
    {
        return array(
            "pregunta_sm_id" => $this->pregunta_sm_id,
            "nombre"         => $this->nombre,
            "valor"          => $this->valor,
        );
    }
    
    public function borrar()
    {
    	$this->delete();
    }
}