<?php $this->headTitle()->prepend('Carreras'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/modules/enc/plantilla/index.css')); ?>

<a class="standard-button" href="crear" title="Crea una nueva carrera">
    <img alt="New" src="<?php echo $this->baseUrl('images/button_add.png'); ?>">
    CREAR CARRERA
</a>

<br />

<div style="margin: 15px auto;">
    <?php if (!count($this->carreras)): ?>
    <div class="warning">
        <img width="50px" alt="Aviso" src="<?php echo $this->baseUrl('images/warning.png'); ?>">
        <br /><h4>Sin carreras.</h4>
    </div>
    <?php else: ?>
    <table>
        <thead>
            <tr>
                <th width="40%">CARRERA</th>
                <th width="20%">CODIGO</th>
                <th width="40%">DEPARTAMENTO</th>
                <th width="10%">EDITAR</th>
                <th width="10%">ELIMINAR</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->carreras as $carrera): ?>
            <tr>
                <td><?php echo $carrera["nombre"]; ?></td>
                <td style="text-align: center;"><?php echo $carrera["codigo"]; ?></td>
                <td><?php echo $carrera["departamento"]; ?></td>
                <td style="text-align: center;">
                    <a href="editar?id=<?php echo $carrera["carrera_id"]; ?>">
                        <img src="<?php echo $this->baseUrl(); ?>/images/page_edit.png" />
                    </a>
                </td>
                <td style="text-align: center;">
                    <a href="borrar?id=<?php echo $carrera["carrera_id"]; ?>">
                        <img src="<?php echo $this->baseUrl(); ?>/images/page_delete.png" />
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</div>

<a class="standard-button" href="crear" title="Crea una nueva carrera">
    <img alt="New" src="<?php echo $this->baseUrl('images/button_add.png'); ?>">
    CREAR CARRERA
</a>