<?php $this->headTitle()->prepend('Plantel Docente'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/modules/enc/plantilla/index.css')); ?>

<div style="margin: 15px auto;">
    <?php if (!count($this->docentes)): ?>
    <div class="warning">
        <img width="50px" alt="Aviso" src="<?php echo $this->baseUrl('images/warning.png'); ?>">
        <br /><h4>Sin docentes.</h4>
    </div>
    <?php else: ?>
    <table>
        <thead>
            <tr>
                <th width="10%">CODIGO</th>
                <th width="35%">DOCENTE</th>
                <th width="35%">EMAIL</th>
                <th width="10%" title="El docente puede ser encuestado por los alumnos">HABILITADO</th>
                <th width="10%">EDITAR</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->docentes as $docente): ?>
            <tr>
                <td style="text-align: center;"><a class="get-link" href="get?id=<?php echo $docente["docente_id"] ?>"><?php echo $docente["codigo"]; ?></a></td>
                <td><a class="get-link" href="get?id=<?php echo $docente["docente_id"] ?>"><?php echo $docente["Persona"]["apellido"] . ', ' . $docente["Persona"]["nombre"]; ?></a></td>
                <td><?php echo $docente["Persona"]["email"]; ?></td>
                <td style="text-align: center;">
                    <a href="activar?id=<?php echo $docente["docente_id"]; ?>">
                        <?php if ($docente["activo"] == 'S'): ?>
                            <img src="<?php echo $this->baseUrl('images/activo.png'); ?>" title="Docente Habilitado" />
                        <?php else: ?>
                            <img src="<?php echo $this->baseUrl('images/no-activo.png'); ?>" title="Docente No Habilitado" />
                        <?php endif; ?>
                    </a>
                </td>
                <td style="text-align: center;">
                    <?php if ($docente["activo"] == 'N'): ?>
                	<a href="editar?id=<?php echo $docente["docente_id"]; ?>">
                	    <img src="<?php echo $this->baseUrl(); ?>/images/page_edit.png" />
					</a>
                	<?php else: ?>
                	<a title="No se pueden editar docentes activos">
                	    <img src="<?php echo $this->baseUrl(); ?>/images/page_edit.png" />
            	    </a>
                	<?php endif; ?>
				</td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</div>