<?php $this->headLink()->appendStylesheet($this->baseUrl('css/modules/inf/informe.css')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('js/modules/inf/informe.js')); ?>

<div id="indice">
	<div class="links">
	    <a href="<?php echo $this->baseUrl('/inf/departamento/get?id=' . $this->data['departamento_id']); ?>">&#x21a9; VOLVER</a>
	    <br/>
	    <a href="<?php echo $this->baseUrl('/inf/departamento/inf-pdf?id=' . $this->data['departamento_id']); ?>">VERSION PDF</a>
		<br/>
	    <a href="<?php echo $this->baseUrl('/inf/departamento/inf-xls?id=' . $this->data['departamento_id']); ?>">VERSION EXCEL</a>
	</div>
	
	<div class="propietario">
		<?php echo $this->data['departamento'] . '<br>' . $this->data['periodo']; ?>
	</div>
    
    <h5>INDICE</h5>
	<ol class="indice">
		<li class="indice"><a id="indice-introduccion">Introducci&oacute;n</a></li>
		<li class="indice"><a id="indice-glosario">Glosario de Conceptos</a></li>
		<li class="indice">
			<a id="indice-perfil">Perfil de los docentes y materias</a>
			<ul>
				<li class="indice"><a id="indice-media-dpto">Nota media del Departamento</a></li>
			</ul>
		</li>
	</ol>
</div>

<div id="informe">
	<div class="oculto" id="introduccion">
		<?php echo $this->introduccion; ?>
		<hr />
		<a class="up">Subir &uarr;</a>
	</div>
	
	<div class="oculto" style="display: none;" id="glosario">
		<?php echo $this->glosario; ?>
		<hr />
		<a class="up">Subir &uarr;</a>
	</div>
	
	<div class="oculto" style="display: none;" id="perfil">
		<?php echo $this->perfil; ?>
		<hr />
		<a class="up">Subir &uarr;</a>
	</div>
	
	<div class="oculto" style="display: none;" id="media-dpto">
	    <?php echo $this->mediaDpto; ?>
	    <hr />
		<a class="up">Subir &uarr;</a>
	</div>
</div>